name: Build raylib WebAssembly

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Install Emscripten SDK
      - name: Install Emscripten
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.sh
          cd ..

      # Clone and build raylib for WebAssembly
      - name: Build raylib for wasm
        run: |
          source emsdk/emsdk_env.sh
          git clone https://github.com/raysan5/raylib.git
          cd raylib
          mkdir build && cd build
          emcmake cmake ..
          emmake make
          cd ../..

      # Build your project using the compiled raylib
      - name: Build project to wasm
        run: |
          source emsdk/emsdk_env.sh
          emcc src/main.cpp -o build/index.html \
            -I raylib/src -L raylib/build/src -lraylib \
            -s USE_WEBGL2=1 -s FULL_ES3=1 -s ALLOW_MEMORY_GROWTH=1 \
            -s WASM=1 -O3

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wasm-build
          path: build/
